.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. nobilitas_qt test_nobilitas_qt
clean: FORCE
	$(MAKE) -C .. nobilitas_qt_clean test_nobilitas_qt_clean
check: FORCE
	$(MAKE) -C .. test_nobilitas_qt_check
nobilitas-qt nobilitas-qt.exe: FORCE
	 $(MAKE) -C .. nobilitas_qt
